import { Flex } from "@chakra-ui/react";
import Head from "next/head";
import PollUser from "../../components/PollCard/poll-user";

//todo update
export async function getStaticPaths() {
  // Return a list of possible value for id
  return {
    paths: [{ params: { id: "1", id: "3" } }],
    fallback: false,
  };
}

export async function getStaticProps(context) {
  return {
    props: {
      title: "hello world",
    }, // will be passed to the page component as props
  };
}

const Poll = (props) => {
  return (
    <>
      <Head>
        <title>Consensays | {props.title}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <Flex
          as={"main"}
          h={"100vh"}
          justifyContent={"center"}
          alignItems={"center"}
          flexDir={"column"}
          gap={5}
          // background={`url(${background})`}
          backgroundSize={"cover"}
          backgroundRepeat={"no-repeat"}
          backgroundPosition={"center"}
        >
          <PollUser setPollView={() => setPollView(VOTE_FORM_VIEW)} />
        </Flex>
      </Head>
    </>
  );
};

export default Poll;
