import { Button, Flex } from "@chakra-ui/react";
import Head from "next/head";
import { useState } from "react";
import PollForm from "../components/PollCard/poll-form";
import PollLayout from "../components/PollCard/poll-layout";
import PollUser from "../components/PollCard/poll-user";
import { AiOutlineArrowLeft } from "react-icons/ai";
import useStore from "../store/store";

export default function Home() {
  const [background, setBackground] = useState(null);
  const [pollSaved, setPollSaved] = useState(false);
  const { colorScheme } = useStore();

  return (
    <>
      <Head>
        <title>Poller</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        as={"main"}
        h={"100vh"}
        justifyContent={"center"}
        alignItems={"center"}
        flexDir={"column"}
        gap={5}
        background={`url(${background})`}
        backgroundSize={"cover"}
        backgroundRepeat={"no-repeat"}
        backgroundPosition={"center"}
      >
        {pollSaved && (
          <Button
            onClick={() => setPollSaved(false)}
            display={"flex"}
            boxShadow={"1px 2px 5px gray"}
            gap={2}
            colorScheme={colorScheme}
          >
            <AiOutlineArrowLeft /> Edit Options
          </Button>
        )}
        <PollLayout pollSaved={pollSaved}>
          {!pollSaved ? (
            <PollForm
              setBackground={(path) => setBackground(path)}
              setPollSaved={() => setPollSaved(true)}
            />
          ) : (
            <PollUser
              colorScheme={colorScheme}
              setPollSaved={() => setPollSaved(false)}
            />
          )}
        </PollLayout>
      </Flex>
    </>
  );
}
