import {Button,} from "@chakra-ui/react";
import Head from "next/head";
import {useState} from "react";
import PollForm from "../components/PollCard/poll-form";
import PollLayout from "../components/Layouts/poll-layout";
import PollUser from "../components/PollCard/poll-user";
import {AiOutlineArrowLeft} from "react-icons/ai";
import {VOTE_USER_VIEW, VOTE_FORM_VIEW} from "../constants/index";
import usePollState from "../store/poll-state.store";
import MainLayout from "../components/Layouts/main-layout";

export default function Home() {
  const [pollView, setPollView] = useState(VOTE_FORM_VIEW);
  const {colorScheme, background} = usePollState();

  return (
    <>
      <Head>
        <title>Consensays</title>
        <meta name='description' content='Generated by create next app'/>
        <meta name='viewport' content='width=device-width, initial-scale=1'/>
        <link rel='icon' href='/favicon.ico'/>
      </Head>
      <MainLayout
        backgroundURL={background}
      >
        {pollView === VOTE_USER_VIEW && (
          <Button
            onClick={() => setPollView(VOTE_FORM_VIEW)}
            display={"flex"}
            boxShadow={"1px 2px 5px gray"}
            gap={2}
            colorScheme={colorScheme}
          >
            <AiOutlineArrowLeft/> Edit Options
          </Button>
        )}
        <PollLayout>
          {pollView === VOTE_FORM_VIEW && (
            <PollForm
              setBackground={(path) => setBackground(path)}
              setPollView={() => setPollView(VOTE_USER_VIEW)}
            />
          )}
          {pollView === VOTE_USER_VIEW && (
            <PollUser previewMode={true}/>
          )}
        </PollLayout>
      </MainLayout>
    </>
  );
}
